---
- name: JenkinsCI | Fetch GPG key
  sudo: yes
  shell: 
    wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
  tags: jenkins-ci

- name: JenkinsCI | Add Jenkins CI repository
  sudo: yes
  shell:
    echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list
  tags: jenkins-ci

- name: JenkinsCI | Install latest Jenkins CI
  sudo: yes
  apt: pkg=jenkins state=latest update-cache=yes
  tags: jenkins-ci

- name: JenkinsCI | Custom Jenkins CI configuration
  sudo: yes
  shell:
    echo 'JAVA_ARGS="-Djava.awt.headless=true -Xmx512m"' >> /etc/default/jenkins
  tags: jenkins-ci

- name: 20s delay while starting Jenkins for the first time
  wait_for: port=8080 delay=10

- name: JenkinsCI | Run Jenkins CI daemon
  sudo: yes
  service: name=jenkins state=restarted
  tags: jenkins-ci
    
# found some problems on Jenkins initialization that has not been fixed yet.
# - name: JenkinsCI | Download jenkins-cli.jar to /opt
#  sudo: yes
#  action: get_url url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/opt mode=0440      
#  tags: jenkins-ci

# - name: JenkinsCI | Install GIT plugin for Jenkins CI 
#  sudo: yes
#  shell:
#    java -jar /opt/jenkins-cli.jar -s http://localhost:8080 install-plugin git
#  tags: jenkins-ci

### Archiva
#- name: JenkinsCI | Download jenkins-cli.jar to /opt
#  sudo: yes
#  action: get_url url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/opt mode=0440      
#  tags: jenkins-ci


