---  
- name: ensure required packages are installed for Java 7 
  sudo: yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - python-apt
 
- name: Add Java repository to sources
  sudo: yes
  shell: add-apt-repository -y ppa:webupd8team/java

- name: Autoaccept license for Java 7 
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
 
- name: Update APT package cache
  sudo: yes
  action: apt update_cache=yes
 
- name: Install Java 7
  sudo: yes
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
 
- name: Set Java 7 Env
  sudo: yes
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes

- name: Install Maven 
  sudo: yes
  action: apt pkg=maven state=latest install_recommends=yes
  tags: maven


