/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.voicetechnology.ng.ipx.ejb.facade;

/**
 * Session layer for AcdGroupServerFacade.
 * @generated 
 * @wtp generated
 */
public class AcdGroupServerFacadeSession
   extends br.com.voicetechnology.ng.ipx.ejb.facade.AcdGroupServerFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
