/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.voicetechnology.ng.ipx.ejb.facade;

/**
 * Session layer for IVRServerFacade.
 * @generated 
 * @wtp generated
 */
public class IVRServerFacadeSession
   extends br.com.voicetechnology.ng.ipx.ejb.facade.IVRServerFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
